fix ci?

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,32 +14,32 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - uses: ./.github/actions/setup
+      - uses: ./.github/actions/
       - run: |
           cp .env.example .env
           pnpm run lint
         shell: bash
 
-  check-changeset:
-    runs-on: ubuntu-latest
-    name: Check Changeset
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - uses: ./.github/actions/setup
+  # check-changeset:
+  #   runs-on: ubuntu-latest
+  #   name: Check Changeset
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - uses: ./.github/actions/
 
-      - name: Check and Validate Changes
-        run: |
-          git fetch origin main:main
-          pnpm changeset status --since origin/main
-          exit_status=$?
-          if [[ $exit_status -eq 0 ]]; then
-            echo "Changeset validation succeeded."
-          else
-            echo "Changeset validation failed."
-          fi
-        shell: bash
+  #     - name: Check and Validate Changes
+  #       run: |
+  #         git fetch origin main:main
+  #         pnpm changeset status --since origin/main
+  #         exit_status=$?
+  #         if [[ $exit_status -eq 0 ]]; then
+  #           echo "Changeset validation succeeded."
+  #         else
+  #           echo "Changeset validation failed."
+  #         fi
+  #       shell: bash
 
   prettier:
     runs-on: ubuntu-latest
@@ -48,7 +48,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - uses: ./.github/actions/setup
+      - uses: ./.github/actions/
 
       - run: pnpm format:check
         shell: bash
@@ -60,7 +60,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - uses: ./.github/actions/setup
+      - uses: ./.github/actions/
 
       - run: pnpm typecheck
         shell: bash
